name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: make toc
    - run: git diff
    - run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes"
        else
          echo "Please update the table of contents with make toc"
          exit 1
        fi
