name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g markdown-toc
      - run: make toc
      - run: git diff --quiet || echo 'toc needs update, run make toc' && exit 1
